### ISSUE TITLE
CounterComponent example stops at 1

### ISSUE THREAD

**Issue by brodybits** [ryansolid/react-solid-state#3]
not sure why, guessing that the setInterval callback is not using the correct setState function after the first callback

**Comment by ryansolid** [comment]
Ok I will look into this tonight. It is definitely surprising, I have an example app that does pretty much exactly that set interval example. In all honesty I need to bring this repo up to the same level of testing that my other repos have.

This repo needs a bit more love in general. I know this is a weird statement to make. But once I made the swap to Hooks, I felt that while there were some benefits using this approach (or even MobX), from React's perspective there is minimal benefit over using the Hooks directly with React.memo. I like how people can try the API but Hooks sort of makes non-React local state management just a complication and will never be as performant as React's own solution.  Historically when React didn't have these fine grained solutions it made a lot of sense, but now not so much.

Global state management is a different thing. It is in no way invalidated by Hooks, but I'm not sure I've given this repo enough consideration to work in that situation.

**Comment by ryansolid** [comment]
I was noticing odd behavior in my initial implementation in a few cases that had led me to doing async updates but just thought it was some quirk of S.js but took it no further because it seemed to work. My playground for trying stuff is this app with web components written in like 15 libraries all working together. Somehow my React Web Component wrapper was working with this example but it was something to do with the wrapper rather than this library. I finally figured out the problem and it's a big one. I solved it but I needed to change how the library works a bit.

In basic, S.js the underlying library is built for SRP. It's synchronicity ensures that like a circuit within a single cycle everything resolves to stable. However, to get it to play nice with Hooks I had to do some pretty interesting tricks to get deps tracking but allow React to re-render itself. In basic the whole component is wrapped in a Computation that fires twice during every update (once to notice the change to tell React to redraw, and then forcefully during redraw to make sure we are tracking the deps). The problem is S doesn't always resolve the values created over these loops until it's done. At which point it triggers a whole other update cycle. What this meant was weirdness with values not being there on first run and things double firing and interrupting each other. I managed to solve all the errors with defered promises but it was still awkward from a performance standpoint in terms of timing.

Luckily there is a way to solve it. It just involves pulling the definitions of signals and effects outside of the observable part. So essentially if the function Component returns a function rather than pure JSX we can just wrap the view in the tracking part allowing the data to fully resolve beforehand. I have made 2 different ways to do this. withSolid still works and has the benefit of using React.memo under the hood, but it can also be done more explicitly with useObserver.

On an aside it looks like the contributors over at the MobX hooks implementation are having similar thoughts. https://github.com/mobxjs/mobx-react-lite/issues/94
